# Stage 1: Build aplikasi React/Vite
FROM oven/bun:1 AS builder
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
# Jalankan proses build Vite (menghasilkan folder /dist)
RUN bun run build

# Stage 2: Sajikan dengan Nginx
FROM nginx:alpine
# Hapus default nginx html
RUN rm -rf /usr/share/nginx/html/*
# Copy hasil build dari Stage 1 ke folder Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy konfigurasi custom Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]