server {
    listen 80;
    server_name localhost; # Nanti akan diakses via IP VPS atau Domain

    # Menyajikan file Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Penting untuk React Router agar tidak error 404 saat direfresh
        try_files $uri $uri/ /index.html; 
    }

    # Reverse Proxy: Arahkan semua request /api ke container Backend
    location /api/ {
        # 'sinari-server' adalah nama container di docker-compose.yml
        proxy_pass http://sinari-server:3000/; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}